language: go

addons:
  postgresql: 9.6

services:
  - postgresql

go:
  - "1.11.x"
  - "1.10.x"
  - master

branches:
  only:
    - master

matrix:
  allow_failures:
    - go: master
fast_finish: true

env:
  DEP_VERSION: "0.5.0"
  MAGE_VERSION: "1.8.0"
  GO11MODULE: "off"

cache:
  directories:
    - $HOME/.cache/go-build
    - vendor

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L -s https://github.com/magefile/mage/releases/download/v${MAGE_VERSION}/mage_${MAGE_VERSION}_Linux-64bit.tar.gz -o mage.tar.gz
  - tar zxvf mage.tar.gz -C $GOPATH/bin/ mage
  - rm -f mage.tar.gz
  - chomd +x $GOPATH/bin/mage

install:
  - mage
  - mage code:vendor

script:
  - mage code:lint
  - mage code:test
