version: '3'
services:
  drunkenfall:
    build: .
    ports:
     - "42001:42001"
    environment:
      DRUNKENFALL_DB_PATH: /drunkenfall/production.db
      DRUNKENFALL_PORT: 42001
      DRUNKENFALL_FACEBOOK_ID: 668534419991204
      DRUNKENFALL_FACEBOOK_SECRET: e74696c890216108c69d55d0e1b7866f
      DRUNKENFALL_FACEBOOK_CALLBACK: http://dev.drunkenfall.com/api/facebook/oauth2callback
      DRUNKENFALL_RABBIT_INCOMING_QUEUE: drunkenfall-app-dev
      DRUNKENFALL_RABBIT_OUTGOING_QUEUE: drunkenfall-game-dev
    volumes:
      - ./data/:/drunkenfall/:rw

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  postgres:
    image: "postgres:10.5-alpine"
    hostname: "postgres"
    ports:
      - "5432:5432"
