version: '3'
services:
  drunkenfall:
    build: .
    ports:
     - "42001:42001"
    environment:
      DF_DB_PATH: /drunkenfall/production.db
      DF_PORT: 42001
      DF_FB_ID: 668534419991204
      DF_FB_SECRET: e74696c890216108c69d55d0e1b7866f
      DF_FB_CALLBACK: http://dev.drunkenfall.com/api/facebook/oauth2callback
    volumes:
      - ./data/:/drunkenfall/:rw

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
